# Generated by Django 2.2.12 on 2021-05-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(max_length=1000),
        ),
    ]
