# Generated by Django 2.2.12 on 2021-05-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20210521_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
    ]
